Flight command
NyliumMC/Essentials pull request #8
Opened 2020-04-27 15:29 UTC by MCrafterzz

Tested it and it works but feel free to totally critizise the code :P

2020-04-27 15:32 UTC, i509VCB commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +        }
Why not make this logic a common private method and keep the feedback and getting the player different between the two executors.

2020-04-27 15:32 UTC, i509VCB commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/entities/EssentialsRegistry.kt
> +        registerCommand(FlightCommand::register)
Does this really belong in essentials base?

2020-04-27 15:33 UTC, Martmists-GH requested changes

2020-04-27 15:33 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +        val player : ServerPlayerEntity = commandContext.source.player
Unnecessary type

2020-04-27 15:33 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +        val player : ServerPlayerEntity = EntityArgumentType.getPlayer(commandContext, "player");
Duplicated code, use a unified method

2020-04-27 15:33 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +                Text.builder {
Use a LiteralText for cases like this

2020-04-27 15:33 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +                    text("Successfully toggled flight for " + player.name.asString())
String formatting > concatenation

2020-04-27 15:39 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +            Pal.revokeAbility(player, VanillaAbilities.ALLOW_FLYING, Pal.getAbilitySource("essentials", "source"))
wrong use of PAL

2020-04-27 15:53 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +                LiteralText("Successfully toggled flight for " + player.name.asString()),
Use string formatting instead of concatenation

2020-04-27 15:53 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +    private lateinit var abilitySource : AbilitySource;
No reason to use lateinit here

2020-04-28 15:13 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +    private var abilitySource : AbilitySource = Pal.getAbilitySource("essentials", "flight");
should be a val

2020-04-28 15:34 UTC, martmists commented on essentials-base/src/main/kotlin/io/github/nyliummc/essentials/commands/FlightCommand.kt
> +    private val abilitySource : AbilitySource = Pal.getAbilitySource("essentials", "flight");
Unnecessary type declaration

2020-04-29 09:59 UTC, merged