Small builder refactors and a Location data class
NyliumMC/Essentials pull request #84
Opened 2020-08-28 19:43 UTC by ItsIlya

**The Refactors**
- ChestGui -> ContainerGui
Container sounds about right for that type of Container-based Gui instead of just calling it ChestGui

- SidebarInfo -> ScoreboardDisplay
Same thing here, ~~Sidebar~~ it's called Scoreboard! And it is definitely not going to be used only for showing info

**Location**
Location data class makes it easier to work with a location in a world.
It contains the position (Vec3d), a dimension (Identifier), a rotation (Vec2f) and a getter for getting the dimension as World.

2020-08-28 20:23 UTC, MaryWeeb requested changes

2020-08-28 20:23 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +    val world: ServerWorld?
Move properties to before companion objects

2020-08-28 20:23 UTC, MaryWeeb commented on gunpowder-base/src/main/kotlin/io/github/gunpowder/entities/GunpowderRegistry.kt
> +import io.github.gunpowder.api.builders.ContainerGui as APIChestGui
Update imported names too

2020-08-28 20:23 UTC, MaryWeeb commented on gunpowder-base/src/main/kotlin/io/github/gunpowder/entities/GunpowderRegistry.kt
> +import io.github.gunpowder.api.builders.ScoreboardDisplay as APISidebarInfo
Ditto

2020-08-28 20:23 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +data class Location(
Try to implement uses for this in various utility functions or extension methods

2020-08-29 11:35 UTC, MaryWeeb requested changes

2020-08-29 11:35 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +        var position: Vec3d,
These should not be mutable. Make functions to offset or change them into new objects.

2020-08-29 11:35 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +        fun dummy() = Location(Vec3d.ZERO, Vec2f.ZERO, World.OVERWORLD.value)
Make this a val instead.

2020-08-29 22:52 UTC, MaryWeeb requested changes

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +        val origin = Location(Vec3d.ZERO, Vec2f.ZERO, World.OVERWORLD.value)
Not sure about this name, would like some more opinions on this. name should probably be capitalized.

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +    fun offset(direction: Direction): Location = Location(
fun offset(direction: Direction) = offset(1.0, direction)

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +    fun offset(amount: Int, direction: Direction): Location = if (amount == 0) this else Location(
No need for `: Location` type specifier

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +    fun axisAlignedRotate(rot: BlockRotation): Location {
Again, no return type needed

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/util/Location.kt
> +    fun withPosition(position: Vec3d) = Location(position, rotation, dimension)
Add a vec3i argument option for Vec3i/BlockPos

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-base/src/main/kotlin/io/github/gunpowder/entities/builders/TeleportRequest.kt
> +            this.destination.withRotation(facing)
You're not setting the values again, fix and test your code.

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-base/src/main/kotlin/io/github/gunpowder/entities/builders/TeleportRequest.kt
> +            this.destination.withDimension(dimension)
Ditto

2020-08-29 22:52 UTC, MaryWeeb commented on gunpowder-base/src/main/kotlin/io/github/gunpowder/entities/builders/TeleportRequest.kt
> +            this.destination
This method does nothing.

2020-09-06 22:40 UTC, ItsIlya commented
Fixed all those and tested.

2020-09-06 23:39 UTC, ItsIlya commented
~~Javadoc~~ KDoc I meant o.o

2020-09-07 00:46 UTC, MaryWeeb commented on gunpowder-api/src/main/kotlin/io/github/gunpowder/api/builders/TeleportRequest.kt
> +    val destination: Location
Make sure to open a PR for this on Gunpowder Teleport as this is a breaking API change.

2020-12-15 00:51 UTC, MaryWeeb commented
Needs reviewing again.

2021-04-14 21:56 UTC, martmists-gh commented
Closing for inactivity

2021-04-14 21:56 UTC, closed without merging